SUPPORT VECTOR MACHINE

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing,svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,classification_report

In [ ]:
data=pd.read_csv("Iris.csv")
data = data.drop("Id", axis=1)

In [ ]:
data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
X=data.iloc[:,0:-1]
X
y = data.iloc[:,-1]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)
print(y)
# X = X.apply(le.fit_transform)
# print(X)

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)
print(xtrain,ytrain)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
41            4.5           2.3            1.3           0.3
94            5.6           2.7            4.2           1.3
40            5.0           3.5            1.3           0.3
18            5.7           3.8            1.7           0.3
73            6.1           2.8            4.7           1.2
..            ...           ...            ...           ...
92            5.8           2.6            4.0           1.2
22            4.6           3.6            1.0           0.2
86            6.7           3.1            4.7           1.5
8             4.4           2.9            1.4           0.2
20            5.4           3.4            1.7           0.2

[120 rows x 4 columns] 41        Iris-setosa
94    Iris-versicolor
40        Iris-setosa
18        Iris-setosa
73    Iris-versicolor
           ...
92    Iris-versicolor
22        Iris-setosa
86    Iris-versicolor
8         Iris-setosa
20        Iris-setosa
Name: Species, Length: 120, dtype: object

In [ ]:
model=svm.SVC()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)

In [ ]:
print(ypred)
print(ytest)

['Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor']
42         Iris-setosa
57     Iris-versicolor
28         Iris-setosa
77     Iris-versicolor
58     Iris-versicolor
93     Iris-versicolor
104     Iris-virginica
81     Iris-versicolor
66     Iris-versicolor
106     Iris-virginica
84     Iris-versicolor
64     Iris-versicolor
6          Iris-setosa
50     Iris-versicolor
125     Iris-virginica
0          Iris-setosa
59     Iris-versicolor
149     Iris-virginica
39         Iris-setosa
135     Iris-virginica
114     Iris-virginica
32         Iris-setosa
113     Iris-virginica
17         Iris-setosa
43         Iris-setosa
23         Iris-setosa
62     Iris-versicolor
13         Iris-setosa
15         Iris-setosa
56     Iris-versicolor
Name: Species, dtype: object

In [ ]:
print(model.score(xtest,ytest))

0.9333333333333333

DATASET

In [ ]:
train_data = pd.read_csv("svm_train.csv")
train_data = train_data.drop("ID", axis = 1)
test_data = pd.read_csv("svm_test.csv")
test_data = test_data.drop("ID", axis = 1)

In [ ]:
train_data.head()

,Sales,CompetitorPrice,Income,Advertising,Population,Price,Location,Age,Education,Urban,US
0,6.01,131,29,11,335,127,Bad,33,12,Yes,Yes
1,6.50,148,51,16,148,150,Medium,58,17,No,Yes
2,7.70,118,71,12,44,89,Medium,67,18,No,Yes
3,7.78,86,54,0,497,64,Bad,33,12,Yes,No
4,11.82,113,66,16,322,74,Good,76,15,Yes,Yes

In [ ]:
test_data.head()

,Sales,CompetitorPrice,Income,Advertising,Population,Price,Location,Age,Education,Urban,US
0,6.39,131,21,8,220,171,Good,29,14,Yes,Yes
1,8.77,118,86,7,265,114,Good,52,15,No,Yes
2,6.89,129,69,10,289,110,Medium,50,16,No,Yes
3,7.96,157,53,0,403,124,Bad,58,16,Yes,No
4,7.57,112,88,2,243,99,Medium,62,11,Yes,Yes

In [ ]:
Xtrain = train_data.iloc[:,1:]
ytrain = train_data.iloc[:,0]
print(Xtrain)
print(ytrain)

     CompetitorPrice  Income  Advertising  Population  Price Location  Age  \
0                131      29           11         335    127      Bad   33
1                148      51           16         148    150   Medium   58
2                118      71           12          44     89   Medium   67
3                 86      54            0         497     64      Bad   33
4                113      66           16         322     74     Good   76
..               ...     ...          ...         ...    ...      ...  ...
344              138      61           12         156    120   Medium   25
345              130      58           19         366    139      Bad   33
346              144      69           11         131    104   Medium   47
347              129      76           16          58    121   Medium   69
348              121      42            4         188    118   Medium   54

     Education Urban   US
0           12   Yes  Yes
1           17    No  Yes
2           18    No  Yes
3           12   Yes   No
4           15   Yes  Yes
..         ...   ...  ...
344         14   Yes  Yes
345         16   Yes  Yes
346         11   Yes  Yes
347         12   Yes  Yes
348         15   Yes  Yes

[349 rows x 10 columns]
0       6.01
1       6.50
2       7.70
3       7.78
4      11.82
       ...
344     9.70
345     5.35
346    11.70
347     8.73
348     5.71
Name: Sales, Length: 349, dtype: float64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# ytrain = le.fit_transform(ytrain)
# print(ytrain)
Xtrain["US"] = le.fit_transform(Xtrain["US"].astype(str))
Xtrain["Location"] = le.fit_transform(Xtrain["Location"].astype(str))
Xtrain["Urban"] = le.fit_transform(Xtrain["US"].astype(str))
print(Xtrain)

     CompetitorPrice  Income  Advertising  Population  Price  Location  Age  \
0                131      29           11         335    127         0   33
1                148      51           16         148    150         2   58
2                118      71           12          44     89         2   67
3                 86      54            0         497     64         0   33
4                113      66           16         322     74         1   76
..               ...     ...          ...         ...    ...       ...  ...
344              138      61           12         156    120         2   25
345              130      58           19         366    139         0   33
346              144      69           11         131    104         2   47
347              129      76           16          58    121         2   69
348              121      42            4         188    118         2   54

     Education  Urban  US
0           12      1   1
1           17      1   1
2           18      1   1
3           12      0   0
4           15      1   1
..         ...    ...  ..
344         14      1   1
345         16      1   1
346         11      1   1
347         12      1   1
348         15      1   1

[349 rows x 10 columns]

In [ ]:
Xtest = train_data.iloc[:,1:]
ytest = train_data.iloc[:,0]
# print(Xtest)
print(ytest)
Xtest["US"] = le.fit_transform(Xtest["US"].astype(str))
Xtest["Location"] = le.fit_transform(Xtest["Location"].astype(str))
Xtest["Urban"] = le.fit_transform(Xtest["US"].astype(str))
# print(Xtest)

0       6.01
1       6.50
2       7.70
3       7.78
4      11.82
       ...
344     9.70
345     5.35
346    11.70
347     8.73
348     5.71
Name: Sales, Length: 349, dtype: float64

In [ ]:
model=svm.SVR()
model.fit(Xtrain,ytrain)
ypred=model.predict(Xtest)
print("the predicted y values: ",ypred)
print("the test y values: ",ytest)
print("the score for the training data set is: ",model.score(Xtest,ytest))
# con_mat = confusion_matrix(ytest,ypred)
# print("Confusion matrix: \n", con_mat)
# print(classification_report(ytest, ypred))

the predicted y values:  [7.17823256 6.61405751 7.44378889 8.13890445 8.00413801 6.29280613
 8.0360242  7.08706991 6.92695453 7.30321461 7.45357922 6.97567764
 7.33897106 6.94990516 7.23529019 7.21564656 7.22923105 6.54299013
 5.81895638 6.47914004 7.60782447 7.01885155 7.43238027 7.61278526
 6.30713447 7.52071791 7.20312894 7.11607029 6.78523594 7.78072011
 7.93252282 6.7680337  7.37013339 6.91861062 7.51065875 7.01110232
 7.89589584 7.6694213  6.93774351 7.66607628 8.07740427 7.36534548
 6.56249502 7.41280663 7.06816312 7.64535161 8.94788452 8.6743437
 7.78620472 7.15181184 8.11151641 6.49332076 7.38672834 7.33930495
 6.95876875 6.91677529 7.72209868 7.24624088 7.63418481 6.18883273
 7.7026028  7.71338686 7.5058663  6.92980117 8.42656064 7.53474328
 6.55894669 8.46654339 7.18009292 7.83682577 7.41734873 7.72387459
 6.44762156 7.11315935 7.70419363 7.43542019 6.93842615 5.88625625
 6.3294047  7.62801028 7.34672918 8.04897606 7.96260786 6.23828456
 7.31538924 7.06322473 7.78264349 7.10859963 7.73238931 7.98767484
 6.68299491 7.43894238 8.22267818 7.65811546 6.98786972 7.95716457
 6.88072088 6.99332772 7.85406143 7.29922501 8.36893203 7.05864379
 8.35692296 6.90483072 7.32784366 7.73334776 7.26161292 8.11974955
 7.13506813 7.00032242 6.9965659  6.80890971 6.9932774  7.21668694
 6.55658971 7.22747654 7.27350929 8.25703954 6.93954548 8.15627402
 7.38193191 8.45759542 7.82390676 6.68502463 8.65277956 7.42151344
 7.89715224 6.31056028 6.96171177 7.47629071 7.72252774 6.66305695
 6.8661595  7.12167524 7.43515043 8.3915132  7.55169451 7.48927166
 7.19236894 7.53948927 7.38072587 7.79095825 8.03739821 8.61098159
 6.99008246 6.96208442 7.216754   7.29085964 8.11465601 7.05742714
 7.36641553 6.71395287 7.34505667 7.16808102 6.54398526 7.29749014
 6.94662345 6.62779443 7.36598754 6.94947997 7.05985852 7.8843097
 7.53160298 6.71083625 7.37104839 7.46566393 7.16549526 6.988173
 6.66046945 7.0903631  7.03229589 6.81008941 7.01149766 8.11758578
 6.92078017 7.32826083 7.4652691  8.90747807 7.01989018 7.2026973
 7.2821153  7.13752784 6.89768335 7.09354406 7.50578998 6.36641158
 8.00010104 7.80581454 6.8794146  8.33423376 6.97334508 6.97411995
 6.85313147 7.29124207 7.41551643 7.50803653 7.30405294 6.78687396
 7.38605668 8.26868409 7.05941662 8.49102891 7.06561831 7.36971464
 6.9400641  7.86486155 7.09779442 6.31460641 7.32195725 7.3125559
 7.71000002 6.72822328 6.89415714 7.35417585 8.69389172 6.18975289
 6.98497112 6.85757087 7.05898862 7.89827656 8.2452905  6.75247007
 6.64969828 7.45458013 7.029006   7.61318508 7.1960559  7.64314787
 7.36861235 7.13995566 7.68476658 7.44180773 7.99894294 6.7326075
 7.29765594 8.6889263  7.89350275 6.80864914 6.37110769 7.31884166
 6.2655148  6.96515069 7.41078707 7.4860384  7.59598728 6.11288786
 8.32301021 7.26629323 6.99113709 7.22527384 7.73946842 6.75825083
 7.31308226 7.54514322 6.61541574 7.30770686 6.64550963 7.69197417
 7.08845813 8.09630004 6.97721981 8.41379752 7.48419589 6.46765346
 6.7573478  7.84059132 8.22860667 7.76571703 7.05790158 7.85246845
 7.70277419 6.91838597 7.53341322 7.44510935 6.58835237 8.15377591
 7.06326308 7.96277758 6.79555991 6.47597448 6.86603064 6.78976421
 7.24763229 7.26555426 6.78173115 7.90170747 8.11347386 6.29128616
 8.01482735 7.02984484 6.88242895 7.35324102 7.0569056  6.88335913
 7.87341178 6.10760509 8.2785896  6.75461452 7.65999935 6.69250071
 7.94675567 7.37061121 7.31919695 7.20024368 7.34182561 7.30759658
 7.97604158 7.56184132 7.26430401 6.7328591  7.4358649  7.52262984
 7.50857347 8.24979477 6.82073746 7.45986305 6.77033831 7.91125391
 6.87310156 4.96482558 6.88973643 7.22049026 6.83032836 6.11285389
 7.32505545 6.93350789 6.42873173 6.96963819 8.36103698 6.24757857
 7.73428339 6.18975616 6.52115825 6.77118991 6.66951156 7.71611411
 8.30434356 8.28661296 7.69907313 6.98912573 8.0400619  6.86657238
 7.32591196 7.45862307 7.89768879 7.1197039  7.96375931 6.88409746
 7.07717785]
the test y values:  0       6.01
1       6.50
2       7.70
3       7.78
4      11.82
       ...
344     9.70
345     5.35
346    11.70
347     8.73
348     5.71
Name: Sales, Length: 349, dtype: float64
the score for the training data set is:  0.21802402746711613